---
- name: Crear entorno virtual
  command: virtualenv /tmp/venv
  args:
    creates: /tmp/venv

- name: Instalar dependencias de Python
  pip:
    requirements: "{{ playbook_dir }}/requirements.txt"
    virtualenv: /tmp/venv
    virtualenv_python: python3

- name: Iniciar la aplicación Flask
  command: /tmp/venv/bin/python {{ playbook_dir }}/app_web/app.py
  args:
    chdir: "{{ playbook_dir }}/app_web"
