---
- name: Instalar virtualenv
  pip:
    name: virtualenv
    state: present

- name: Crear entorno virtual
  command: virtualenv /tmp/venv
  args:
    creates: /tmp/venv

- name: Instalar dependencias de Python en el entorno virtual
  pip:
    requirements: "{{ playbook_dir }}/requirements.txt"
    virtualenv: /tmp/venv
    virtualenv_python: python3

- name: Iniciar la aplicación Flask
  shell: |
    FLASK_APP={{ playbook_dir }}/app_web/app.py /tmp/venv/bin/python -m flask run --host=0.0.0.0 --port=5000 &
  args:
    chdir: "{{ playbook_dir }}/app_web"
