- name: Instalamos Python 3
  apt:
    name: python3
    state: present

- name: Instalamos pip para instalar librerias y virtualenv para crear entornos virtuales
  apt:
    name:
      - python3-pip
      - virtualenv
    state: present

- name: Creamos el entorno virtual
  command: virtualenv /tmp/venv
  args:
    creates: /tmp/venv

- name: Instalamos los módulos que necesitamos para nuestra aplicación con el requirements.txt dentro del virtualenv
  pip:
    requirements: /path/to/requirements.txt
    virtualenv: /path/to/venv
